---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-devices-config
  namespace: {{ .Values.namespace }}
data:
  .env: |-
    MONGODB_URL={{ .Values.mongodbUrl }}
    {{- if .Values.domains.mqtt.ssl.enable }}
    MQTT_URL=mqtts://{{ .Values.domains.mqtt.name }}
    MQTT_PORT=8883
    MQTT_TLS=true
    {{- if eq "prod" .Values.letsencrypt.server.env  }}
    MQTT_CA_FILE=/etc/ssl/certs/ISRG_Root_X1.pem
    {{ else }}
    MQTT_CA_FILE=/tls-cert/tls.crt
    {{ end -}}
    MQTT_CERT_FILE=/tls-cert/tls.crt
    MQTT_KEY_FILE=/tls-cert/tls.key
    {{ else }}
    MQTT_URL=mqtt://mosquitto-svc.{{ .Values.namespace }}.svc.cluster.local
    MQTT_PORT=1883
    MQTT_TLS=false
    MQTT_CA_FILE=
    MQTT_CERT_FILE=
    MQTT_KEY_FILE=
    {{ end -}}
    MQTT_CLIENT_ID=apiDevices
    {{- if .Values.mosquitto.auth.enable }}
    MQTT_AUTH=true
    MQTT_USER={{ .Values.mosquitto.auth.username }}
    MQTT_PASSWORD={{ .Values.mosquitto.auth.password }}
    {{ else }}
    MQTT_AUTH=false
    MQTT_USER=
    MQTT_PASSWORD=
    {{ end -}}
    GRPC_URL=0.0.0.0:50051
    GRPC_TLS=false
    CERT_FOLDER_PATH=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-devices
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-devices
  template:
    metadata:
      labels:
        app: api-devices
    spec:
      initContainers:
        - name: init-certs
          image: alpine
          command: 
            - "/bin/sh"
            - "-c"
            - |
              cp /etc/tls/cert-issuer-mqtt/tls.crt /tls-cert/tls.crt
              cp /etc/tls/cert-issuer-mqtt/tls.key /tls-cert/tls.key
          volumeMounts:
            - name: tls
              mountPath: /tls-cert
            - name: certmqtt
              mountPath: /etc/tls/cert-issuer-mqtt
      containers:
      - name: api-devices
        image: {{ .Values.apiDevices.image }}
        imagePullPolicy: Always
        env:
        - name: ENV
          value: "prod"
        {{- if .Values.apiDevices.grpc.libraryLogEnable }}
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: "info"
        - name: GRPC_GO_LOG_VERBOSITY_LEVEL
          value: "2"
        {{- end }}
        ports:
        - name: grpc
          containerPort: 50051
          protocol: TCP
        volumeMounts:
          - name: api-devices-config
            mountPath: /.env
            subPath: .env
            readOnly: true
          - name: tls
            mountPath: /tls-cert
      volumes:
        - name: api-devices-config
          configMap:
            name: api-devices-config
        - name: certmqtt
          secret:
            secretName: mqtt-tls
        - name: tls
          emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: api-devices-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: api-devices
  ports:
  - name: grpc
    protocol: TCP
    port: 50051
    targetPort: grpc