---
apiVersion: v1
kind: Secret
metadata:
  name: consumer-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  .env: |-
    LOG_LEVEL=info
    MONGO_URI={{ .Values.mongodbUrl }}
    MONGO_DB_NAME=sensors
    REDIS_URI=redis://{{ .Values.redis.serviceName }}.{{ .Values.namespace }}.svc.cluster.local:6379
    REDIS_USERNAME={{ .Values.redis.username }}
    REDIS_PASSWORD={{ .Values.redis.password }}
    AMQP_URI=amqp://{{ .Values.rabbitmq.consumer.user }}:{{ .Values.rabbitmq.consumer.password }}@rabbitmq.{{ .Values.namespace }}.svc.cluster.local:5672
    AMQP_HMAC_SECRET={{ .Values.rabbitmq.amqpHmacSecret }}
    AMQP_QUEUE_NAME=ks89
    AMQP_CONSUMER_TAG=consumer
    API_TOKEN_HASH_SECRET={{ .Values.apiToken.hashSecret }}
    API_TOKEN_ENCRYPTION_KEY={{ .Values.apiToken.encryptionKey }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      {{- if .Values.serviceAccounts.enabled }}
      serviceAccountName: consumer
      automountServiceAccountToken: false
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: consumer
        image: {{ .Values.consumer.image }}
        {{- if .Values.debug.pods.alwaysPullContainers }}
        imagePullPolicy: Always
        {{- end }}
        {{- if .Values.debug.pods.sleepInfinity }}
        command: ["/bin/sh"]
        args: ["-c", "chmod +x /app/consumer; /app/consumer; sleep Infinity;"]
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
            add: ["NET_BIND_SERVICE"]
        resources:
          {{- toYaml .Values.consumer.resources | nindent 10 }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: consumer-secret
          mountPath: /app/.env
          subPath: .env
          readOnly: true
        - name: tmp
          mountPath: /tmp
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: consumer-secret
        secret:
          secretName: consumer-secret
      - name: tmp
        emptyDir: {}
      - name: logs
        emptyDir: {}
