---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  {{- if .Values.domains.http.ssl.enable }}
  annotations:
    cert-manager.io/issuer: "cert-issuer-webapp"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/redirect-to-https: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Frame-Options "sameorigin";
      add_header X-Content-Type-Options nosniff;
      add_header Referrer-Policy 'same-origin';
      add_header Permissions-Policy "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()";
  {{- end }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: http-nginx
  {{- if .Values.domains.http.ssl.enable }}
  tls:
  - hosts:
    - {{ .Values.domains.http.name }}
    secretName: webapp-tls
  {{- end }}
  rules:
  - host: {{ .Values.domains.http.name }}
    http:
      paths:
      # use the gui nginx server as backend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gui-svc
            port:
              number: 80
{{- if .Values.domains.http.ssl.enable }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-issuer-webapp
  namespace: {{ .Values.namespace }}
spec:
  acme:
    server: {{ .Values.letsencrypt.server.path }}
    email: {{ .Values.letsencrypt.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: cert-issuer-webapp
    solvers:
      - http01:
          ingress:
            ingressClassName: http-nginx
{{- end }}