---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mqtt-ingress
  {{- if .Values.domains.mqtt.ssl.enable }}
  annotations:
    cert-manager.io/issuer: "cert-issuer-mqtt"
  {{- end }}
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: mqtt-nginx
  {{- if .Values.domains.mqtt.ssl.enable }}
  tls:
  - hosts:
    - {{ .Values.domains.mqtt.name }}
    secretName: mqtt-tls
  {{- end }}
  rules:
  - host: {{ .Values.domains.mqtt.name }}
    http:
      paths:
      # use the gui nginx server as backend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mosquitto-svc
            port:
              {{- if .Values.domains.mqtt.ssl.enable }}
              number: 8883
              {{- else }}
              number: 1883
              {{- end }}
{{- if .Values.domains.mqtt.ssl.enable }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cert-issuer-mqtt
  namespace: {{ .Values.namespace }}
spec:
  acme:
    server: {{ .Values.letsencrypt.server.path }}
    email: {{ .Values.letsencrypt.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: cert-issuer-mqtt
    solvers:
      - http01:
          ingress:
            ingressClassName: mqtt-nginx
{{- end }}