apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mosquitto-data-claim
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.storageClassName | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
