apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      containers:
      - name: mosquitto
        image: {{ .Values.mosquitto.image }}
        {{- if .Values.mosquitto.ssl.enable }}
        env:
        - name: CERTBOT_EMAIL
          value: {{ .Values.mosquitto.ssl.certbot.email }}
        - name: CERTBOT_DOMAIN
          value: {{ .Values.domains.mqtt }}
        - name: CERTBOT_SERVER
          # use https://acme-staging-v02.api.letsencrypt.org/directory for staging server
          value: {{ .Values.mosquitto.ssl.certbot.server }}
        {{- end }}
        ports:
        # port 80 is required by certbot to get and renew certificates
        - name: http
          containerPort: 80
          protocol: TCP
        {{- if .Values.mosquitto.ssl.enable }}
        - name: mqtts
          containerPort: 8883
          protocol: TCP
        {{- else }}
        - name: mqtt
          containerPort: 1883
          protocol: TCP
        {{- end }}
        {{ if .Values.mosquitto.ssl.enable }}
        volumeMounts:
          - name: lets-encrypt-ssl-mqtt-storage
            mountPath: "/etc/letsencrypt/"
        {{ end }}
      {{ if .Values.mosquitto.ssl.enable }}
      volumes:
        - name: lets-encrypt-ssl-mqtt-storage
          persistentVolumeClaim:
            claimName: lets-encrypt-ssl-mqtt-claim
      {{ end }}
---
kind: Service
apiVersion: v1
metadata:
  name: mosquitto-svc
  namespace: {{ .Values.namespace }}
spec:
  loadBalancerIP: {{ .Values.mosquitto.publicIp }}
  type: LoadBalancer
  selector:
    app: mosquitto
  ports:
    # port 80 is required by certbot to get and renew certificates
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    {{- if .Values.mosquitto.ssl.enable }}
    # expose mqtts port
    - name: mqtts
      protocol: TCP
      port: 8883
      targetPort: mqtts
    {{- else }}
    # expose mqtt port
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: mqtt
    {{- end }}