---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: {{ .Values.namespace }}
data:
  mosquitto.conf: |-
    persistence true
    persistence_location /mosquitto/data
    allow_anonymous true
    connection_messages true
    log_type all

    {{- if .Values.domains.mqtt.ssl.enable }}
    # secure connection are available externally
    listener 8883
    # taken from https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-the-mosquitto-mqtt-messaging-broker-on-ubuntu-18-04
    # I need to copy let's encrypt files to another destination to be able
    # to set right owner and permissions
    certfile /etc/mosquitto/certs/tls.crt
    {{- if eq "prod" .Values.letsencrypt.server.env  }}
    cafile /etc/ssl/certs/ca-certificates.crt
    {{- else }}
    cafile /etc/tls/cert-issuer-mqtt/tls.crt
    {{- end }}
    keyfile /etc/mosquitto/certs/tls.key
    {{- else }}
    # insecure connections via 1883 disabled
    listener 1883
    {{- end }}

    {{- if .Values.mosquitto.auth.enable }}
    password_file /etc/mosquitto/password_file
    {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      securityContext:
        # The owner for volumes and any files created in that volume will be Group ID 1883 (mosquitto)
        fsGroup: 1883
      containers:
      - name: mosquitto
        image: {{ .Values.mosquitto.image }}
        imagePullPolicy: Always
        readinessProbe:
          exec:
            command:
            - mosquitto_pub
            - -h
            - localhost
            - -p
            - "{{ .Values.domains.mqtt.ssl.enable | ternary 8883 1883 }}"
            - -u
            - "{{ .Values.mosquitto.auth.username }}"
            - -P
            - "{{ .Values.mosquitto.auth.password }}"
            - -m
            - "readiness_probe"
            - -t
            - readiness
            - --insecure
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - mosquitto_pub
            - -h
            - localhost
            - -p
            - "{{ .Values.domains.mqtt.ssl.enable | ternary 8883 1883 }}"
            - -u
            - "{{ .Values.mosquitto.auth.username }}"
            - -P
            - "{{ .Values.mosquitto.auth.password }}"
            - -m
            - "readiness_probe"
            - -t
            - readiness
            - --insecure
          periodSeconds: 60
        env:
        {{ if .Values.domains.mqtt.ssl.enable }}
        - name: MOSQUITTO_SSL_ENABLE
          value: "true"
        {{- end }}
        {{- if .Values.mosquitto.auth.enable }}
        - name: MOSQUITTO_USERNAME
          value: {{ .Values.mosquitto.auth.username }}
        - name: MOSQUITTO_PASSWORD
          value: {{ .Values.mosquitto.auth.password }}
        {{- end }}
        ports:
        - name: {{ .Values.domains.mqtt.ssl.enable | ternary "mqtts" "mqtt" }}
          containerPort: {{ .Values.domains.mqtt.ssl.enable | ternary 8883 1883 }}
          protocol: TCP
        volumeMounts:
          - name: data
            mountPath: "/mosquitto/data"
          - name: mosquitto-config
            mountPath: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
            readOnly: true
          {{- if .Values.domains.mqtt.ssl.enable }}
          - name: certmqtt
            mountPath: /etc/mosquitto/certs/
          {{- end }}
      {{- if .Values.domains.mqtt.ssl.enable }}
      - name: k8s-config-reloader
        image: {{ .Values.k8sConfigReloader.image }}
        env:
          - name: CONFIG_DIR
            value: >-
              /etc/mosquitto/certs/tls.key,/etc/mosquitto/certs/tls.crt
          - name: PROCESS_NAME
            value: mosquitto
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
              - KILL
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: false
        volumeMounts:
          - mountPath: /config/
            name: mosquitto-config
            readOnly: true
          - name: certmqtt
            mountPath: /etc/mosquitto/certs/
      {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto-data-claim
        - name: mosquitto-config
          configMap:
            name: mosquitto-config
        {{- if .Values.domains.mqtt.ssl.enable }}
        - name: certmqtt
          secret:
            secretName: mqtt-tls
            defaultMode: 0600
        {{- end }}
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.mosquitto.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mosquitto
  ports:
    {{- if .Values.domains.mqtt.ssl.enable }}
    # expose mqtts port
    - name: mqtts
      protocol: TCP
      port: 8883
      targetPort: mqtts
    {{- else }}
    # expose mqtt port
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: mqtt
    {{- end }}