apiVersion: v1
kind: ResourceQuota
metadata:
  name: home-anthill-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    pods: "30"
    requests.cpu: "4"
    requests.memory: "8Gi"
    limits.cpu: "8"
    limits.memory: "16Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: home-anthill-limits
  namespace: {{ .Values.namespace }}
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 64Mi
      default:
        cpu: 500m
        memory: 512Mi
      min:
        cpu: 5m
        memory: 16Mi
      max:
        cpu: 2
        memory: 2Gi