kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: latest
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/audit-version: latest
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
