---
apiVersion: v1
kind: ConfigMap
metadata:
  name: producer-config
  namespace: {{ .Values.namespace }}
data:
  .env: |-
    AMQP_URI=amqp://rabbitmq-svc.{{ .Values.namespace }}.svc.cluster.local:5672
    AMQP_QUEUE_NAME=ks89
    {{- if .Values.domains.mqtt.ssl.enable }}
    MQTT_URL={{ .Values.domains.mqtt.name }}
    MQTT_PORT=8883
    MQTT_TLS=true
    {{- if eq "prod" .Values.letsencrypt.server.env  }}
    ROOT_CA=/etc/ssl/certs/ISRG_Root_X1.pem
    {{ else }}
    ROOT_CA=/tls/tls.crt
    {{ end -}}
    MQTT_CERT_FILE=/tls/tls.crt
    MQTT_KEY_FILE=/tls/tls.key
    {{ else }}
    MQTT_URL=mosquitto-svc.{{ .Values.namespace }}.svc.cluster.local
    MQTT_PORT=1883
    MQTT_TLS=false
    ROOT_CA=
    MQTT_CERT_FILE=
    MQTT_KEY_FILE=
    {{ end -}}
    MQTT_CLIENT_ID=producer
    {{- if .Values.mosquitto.auth.enable }}
    MQTT_AUTH=true
    MQTT_USER={{ .Values.mosquitto.auth.username }}
    MQTT_PASSWORD={{ .Values.mosquitto.auth.password }}
    {{ else }}
    MQTT_AUTH=false
    MQTT_USER=
    MQTT_PASSWORD=
    {{ end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: {{ .Values.producer.image }}
        {{- if .Values.debug.pods.alwaysPullContainers }}
        imagePullPolicy: Always
        {{- end }}
        {{- if .Values.debug.pods.sleepInfinity }}
        command: ["/bin/sh"]
        args: ["-c", "chmod +x /app/producer; /app/producer; sleep Infinity;"]
        {{- end }}
        ports:
        - name: amqp
          containerPort: 5672
          protocol: TCP
        {{- if .Values.domains.mqtt.ssl.enable }}
        - name: mqtts
          containerPort: 8883
          protocol: TCP
        {{- else }}
        - name: mqtt
          containerPort: 1883
          protocol: TCP
        {{- end }}
        volumeMounts:
        - name: producer-config
          mountPath: /app/.env
          subPath: .env
          readOnly: true
        {{ if .Values.domains.mqtt.ssl.enable }}
        # mount tls certificate to be read from the app
        - name: tls
          # mount certificates here, but the container run.sh script
          # will copy these files to be used by mosquitto
          mountPath: "/tls"
          readOnly: true
        {{ end }}
      volumes:
      - name: producer-config
        configMap:
          name: producer-config
      {{ if .Values.domains.mqtt.ssl.enable }}
      # volume to get tls certificate from certmanager via csi-driver
      - name: tls
        csi:
          driver: csi.cert-manager.io
          readOnly: true
          volumeAttributes:
            csi.cert-manager.io/issuer-name: cert-issuer-mqtt
            csi.cert-manager.io/dns-names: "{{ .Values.domains.mqtt.name }}"
      {{ end }}
---
kind: Service
apiVersion: v1
metadata:
  name: producer-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: producer
  ports:
    {{- if .Values.domains.mqtt.ssl.enable }}
    # expose mqtts port
    - name: mqtts
      protocol: TCP
      port: 8883
      targetPort: mqtts
    {{- else }}
    # expose mqtt port
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: mqtt
    {{- end }}
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: amqp
