---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.rabbitmq.user }}
  password: {{ .Values.rabbitmq.password }}
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespace }}
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rabbitmq-user
  namespace: {{ .Values.namespace }}
spec:
  tags:
  - management
  - policymaker
  - monitoring
  - administrator
  rabbitmqClusterReference:
    name: rabbitmq
  importCredentialsSecret:
    name: rabbitmq-secret
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-permission
  namespace: {{ .Values.namespace }}
spec:
  vhost: "/"
  user: "{{ .Values.rabbitmq.user }}"
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq

