---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.rabbitmq.user }}
  password: {{ .Values.rabbitmq.password }}
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: {{ .Values.namespace }}
spec:
  resources:
    requests:
      cpu: {{ .Values.rabbitmq.resources.requests.cpu | quote }}
      memory: {{ .Values.rabbitmq.resources.requests.memory | quote }}
    limits:
      cpu: {{ .Values.rabbitmq.resources.limits.cpu | quote }}
      memory: {{ .Values.rabbitmq.resources.limits.memory | quote }}
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rabbitmq-user
  namespace: {{ .Values.namespace }}
spec:
  tags:
  - management
  - policymaker
  - monitoring
  - administrator
  rabbitmqClusterReference:
    name: rabbitmq
  importCredentialsSecret:
    name: rabbitmq-secret
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-permission
  namespace: {{ .Values.namespace }}
spec:
  vhost: "/"
  user: "{{ .Values.rabbitmq.user }}"
  permissions:
    write: ".*"
    configure: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-producer-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.rabbitmq.producer.user }}
  password: {{ .Values.rabbitmq.producer.password }}
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rabbitmq-producer-user
  namespace: {{ .Values.namespace }}
spec:
  tags: []
  rabbitmqClusterReference:
    name: rabbitmq
  importCredentialsSecret:
    name: rabbitmq-producer-secret
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-producer-permission
  namespace: {{ .Values.namespace }}
spec:
  vhost: "/"
  user: "{{ .Values.rabbitmq.producer.user }}"
  permissions:
    write: "^(amq\\.default|ks89)$"
    configure: "^ks89$"
    read: "^ks89$"
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-consumer-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  username: {{ .Values.rabbitmq.consumer.user }}
  password: {{ .Values.rabbitmq.consumer.password }}
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: rabbitmq-consumer-user
  namespace: {{ .Values.namespace }}
spec:
  tags: []
  rabbitmqClusterReference:
    name: rabbitmq
  importCredentialsSecret:
    name: rabbitmq-consumer-secret
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: rabbitmq-consumer-permission
  namespace: {{ .Values.namespace }}
spec:
  vhost: "/"
  user: "{{ .Values.rabbitmq.consumer.user }}"
  permissions:
    write: ""
    configure: "^ks89$"
    read: "^ks89$"
  rabbitmqClusterReference:
    name: rabbitmq
