---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: {{ .Values.namespace }}
data:
  redis.conf: |-
    dbfilename snapshot.rdb
    # save snapshot if 1 keys has ve been modified in 120 seconds
    save 120 1
    protected-mode no
    bind 0.0.0.0
    user {{ .Values.redis.username }} on >{{ .Values.redis.password }} ~* +@all
    user default off
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      {{- if .Values.dhi.enabled }}
      imagePullSecrets:
        - name: dhi-registry-secret
      {{- end }}
      {{- if .Values.dhi.enabled }}
      securityContext:
        fsGroup: 999 # 999 = the redis group in the hardened image
        runAsUser: 999
        runAsGroup: 999
      {{- end }}
      containers:
      - name: redis
        image: {{ if .Values.dhi.enabled }}{{ .Values.redis.hardenedImage }}{{ else }}{{ .Values.redis.image }}{{ end }}
        imagePullPolicy: Always
        readinessProbe:
          exec:
            command:
            - redis-cli
            - --user
            - {{ .Values.redis.username }}
            - -a
            - {{ .Values.redis.password }}
            - --no-auth-warning
            - ping
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - redis-cli
            - --user
            - {{ .Values.redis.username }}
            - -a
            - {{ .Values.redis.password }}
            - --no-auth-warning
            - ping
          periodSeconds: 60
        # start redis with a custom redis.conf file
        command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
        ports:
        - name: "redis-port"
          containerPort: 6379
          protocol: TCP
        volumeMounts:
          - name: data
            mountPath: "/data"
          - name: redis-config
            mountPath: /usr/local/etc/redis/redis.conf
            subPath: redis.conf
            readOnly: true
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis-data-claim
        - name: redis-config
          configMap:
            name: redis-config
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.redis.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: redis
  ports:
    - name: redis-port
      protocol: TCP
      port: 6379
      targetPort: redis-port