---
apiVersion: v1
kind: ConfigMap
metadata:
  name: register-config
  namespace: {{ .Values.namespace }}
data:
  .env: |-
    MONGO_URI={{ .Values.mongodbUrl }}
    MONGO_DB_NAME=sensors
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: register
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register
  template:
    metadata:
      labels:
        app: register
    spec:
      containers:
      - name: register
        image: {{ .Values.register.image }}
        {{- if .Values.debug.pods.alwaysPullContainers }}
        imagePullPolicy: Always
        {{- end }}
        {{- if .Values.debug.pods.sleepInfinity }}
        command: ["/bin/sh"]
        args: ["-c", "chmod +x /app/register; /app/register; sleep Infinity;"]
        {{- end }}
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: rabbitmqgui
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: register-config
          mountPath: /app/.env
          subPath: .env
          readOnly: true
      volumes:
      - name: register-config
        configMap:
          name: register-config
---
kind: Service
apiVersion: v1
metadata:
  name: register-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: register
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: rabbitmqgui
      protocol: TCP
      port: 8080
      targetPort: http