---
apiVersion: v1
kind: ConfigMap
metadata:
  name: register-config
  namespace: {{ .Values.namespace }}
data:
  .env: |-
    MONGO_URI={{ .Values.mongodbUrl }}
    MONGO_DB_NAME=sensors
  Rocket.toml: |-
    [default]

    [debug]
    secret_key="{{ .Values.register.rocketSecretKey.debug }}"

    [release]
    address = "0.0.0.0"
    port = 80
    secret_key="{{ .Values.register.rocketSecretKey.release }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: register
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: register
  template:
    metadata:
      labels:
        app: register
    spec:
      containers:
      - name: register
        image: {{ .Values.register.image }}
        {{- if .Values.debug.pods.alwaysPullContainers }}
        imagePullPolicy: Always
        {{- end }}
        {{- if .Values.debug.pods.sleepInfinity }}
        command: ["/bin/sh"]
        args: ["-c", "chmod +x /app/register; /app/register; sleep Infinity;"]
        {{- end }}
        readinessProbe:
          httpGet:
            path: /keepalive
            port: http
          periodSeconds: 30
        livenessProbe:
          httpGet:
            path: /keepalive
            port: http
          periodSeconds: 60
          failureThreshold: 2
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: rabbitmqgui
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: register-config
          mountPath: /app/.env
          subPath: .env
          readOnly: true
        - name: register-config
          mountPath: /app/Rocket.toml
          subPath: Rocket.toml
          readOnly: true
      volumes:
      - name: register-config
        configMap:
          name: register-config
---
kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.register.serviceName }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: register
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: rabbitmqgui
      protocol: TCP
      port: 8080
      targetPort: http