# Default values for home-anthill.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: home-anthill
domainName: "your-domain.com"

domains:
  http: "your-domain.com"
  mqtt: "mqtt-domain.com"

mosquitto:
  image: "ks89/mosquitto:v1.0.0-beta.1"
  letsEncryptCerts: "/root/lets-encrypt-certs-mqtt"
  publicIp: "9.8.7.6"
  dataFolder: "/root/mosquitto-persistence-data"
  auth:
    enable: true
    username: "mosquser"
    password: "Password1!"
  ssl:
    enable: false
    certbot:
      email: "your.email@emailexample.com"
      # staging server is https://acme-staging-v02.api.letsencrypt.org/directory
      server: "https://acme-v02.api.letsencrypt.org/directory"

apiDevices:
  image: "ks89/api-devices:v1.0.0-beta.2"
  grpc: 
    libraryLogEnable: false

apiServer:
  image: "ks89/api-server:v1.0.0-beta.2"
  singleUserLoginEmail: "your.email@emailexample.com"
  jwtPassword: "D%$ZmPh@6WMc$=@!a-pQaa_+?zu4+3iF"
  cookieSecret: "@DbTN*jA"
  oauth2ClientID: "6caa41f023f6205b1c05"
  oauth2SecretID: "5ac42264964d85e4c2e938b4534d02f4d2b8b336"
  grpc: 
    libraryLogEnable: false
  sensors:
    enable: true

gui:
  image: "ks89/gui:v1.0.0-beta.2"
  nginxConf: "/root/nginx-conf"
  letsEncryptCerts: "/root/lets-encrypt-certs"
  publicIp: "1.2.3.4"
  ssl:
    enable: false
    certbot:
      email: "your.email@emailexample.com"
      # staging server is https://acme-staging-v02.api.letsencrypt.org/directory
      server: "https://acme-v02.api.letsencrypt.org/directory"

mongodbUrl: "mongodb+srv://user:password@cluster0.1234.mongodb.net"

rabbitmq:
  image: "rabbitmq:3-management"
  user: "guest"
  password: "guest"

register:
  image: "ks89/register:v1.0.0-beta.1"

producer:
  image: "ks89/producer:v1.0.0-beta.1"

consumer:
  image: "ks89/consumer:v1.0.0-beta.1"

# debug configuration, not for production environment
debug:
  pods:
    alwaysPullContainers: false
    # if your pods are crashing, you can enable this to prevent restarts
    # and to access them using your terminal.
    # Don't enable this on a production environment!!!
    sleepInfinity: false